version: '3'
services:
  myproject_web:
    build: ./php
    image: myproject_web_php:latest
    container_name: myproject_web
    hostname: "myproject_web"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on:
      - web_db
  web_db:
    image: mariadb:10.2
    container_name: web_db
    restart: unless-stopped
    tty: true
    ports:
      - "23106:3306"
    volumes:
      - ./web_db/data:/var/lib/mysql
      - ./web_db/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: fajri
      MYSQL_PASSWORD: p455w0rd1!.
      MYSQL_ROOT_PASSWORD: p455w0rd
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  nginx_myproject_web:
    build: ./nginx
    image: nginx_myproject_web:latest
    container_name: nginx_myproject_web
    hostname: "nginx_myproject_web"
    ports:
      - "52:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - myproject_web
